spring:
  data:
    neo4j:
      username: neo4j
      password: password
      uri: http://localhost:7474
    cassandra:
      keyspace-name: cover_typee
      contact-points: localhost
      port: 9042
      schema-action: create_if_not_exists

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest


config:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    client:
      id: KafkaProducer
    serializer:
      key: org.apache.kafka.common.serialization.IntegerSerializer
      value: org.apache.kafka.common.serialization.StringSerializer
    topic: test
  rabbitmq:
    queue: notification

storage:
  media: test
keycloak:
  auth-server-url: http://localhost:8089/auth
  realm: social-network
  resource: social-network
  public-client: true
  principal-attribute: fullName
  enable-basic-auth: true
  security-constraints[0]:
    authRoles[0]: R_USER
    securityCollections[0]:
      patterns[0]: /user/
logging:
  file: /var/log/app-mix/logs/application.log