spring:
  data:
    neo4j:
      username: neo4j
      password: password
      uri: http://localhost:7474

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

storage:
  media: test

keycloak:
  auth-server-url: http://localhost:8089/auth
  realm: social-network
  resource: social-network
  public-client: true
  principal-attribute: fullName
  enable-basic-auth: true
  security-constraints[0]:
    authRoles[0]: R_USER
    securityCollections[0]:
      patterns[0]: /user/