version: '2'

services:
  db:
    image: mysql:latest
    volumes:
      - $PWD/docker/mysql/db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: oauth
      MYSQL_USER: oauth
      MYSQL_PASSWORD: oauth1234
  mongorep_1:
    image: mongo:latest
    container_name: "mongorep_1"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - $PWD/docker/mongo/mongorep1/data/:/data/db
    ports:
      - 27017:27017
    hostname: 192.168.0.20
    command: mongod --replSet mon --smallfiles --logpath=/dev/null
  dbpostgres:
    image: postgres
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
      - POSTGRES_ROOT_PASSWORD=root_password
  keycloak:
    image: jboss/keycloak
    environment:
      - KEYCLOAK_LOGLEVEL=DEBUG
    links:
      - dbpostgres:postgres
    ports:
      - "8089:8080"
      - "9999:9990"
      - "443:8443"
    volumes:
      - $PWD/docker/keycl
  neo4j:
    image: neo4j:3.0
    ports:
    - "7474:7474"
    - "7687:7687"
    volumes:
      - $PWD/docker/neo4j/db/dbms:/data/dbms
  rabbit:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    environment:
      RABBITMQ_ERLANG_COOKIE: "RABBITMQWORK"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    volumes:
      - $PWD/docker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins"
  elasticsearch:
    image: elasticsearch:2.4.6-alpine
    command: elasticsearch -Des.network.host=0.0.0.0
    ports:
      - "9200:9200"
      - "9300:9300"
    volume_driver: flocker
    volumes:
      - $PWD/docker/elasticsearch:/usr/share/elasticsearch/data
  logstash:
    image: logstash:2.4.1-alpine
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - $PWD/docker/logstash/logstash.conf:/etc/logstash/conf.d/logstash.conf
      - $PWD/docker/logstash/logs/:/logs/
    ports:
      - "5000:5000"
    links:
      - elasticsearch
  kibana:
    image: kibana:4.6.6
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://172.17.0.1:9200